spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 430351240036-3bnavqmpu11omcnnhoda3252q62c2ukt.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "http://localhost:8080/api/v1/auth/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret: your_secret_key
  expiration: 3600000 # 1 hour in milliseconds
